name: 'release-matrix-action'
description: 'GitHub Action to generate matrix using "endoflife-date/release-data" dataset'
branding:
  icon: 'tag'
  color: 'white'
inputs:
  search:
    description: 'The search keyword for release data'
    required: true
  date:
    description: 'Set the filter for the release by date, e.g: 2023-01-01, 2023'
    required: false
  version:
    description: 'Set the filter for the release by version, e.g: 1.0'
    required: false
  limit:
    description: 'Set the limit for the number of releases to output, default: 3'
    required: false
  strict:
    description: 'Enable strict mode for the search, will throw if no release were found. default: false'
    required: false
    default: "false"
outputs:
  matrix:
    description: 'The release matrix data'
  version:
    description:  'The release versions'
runs:
  using: 'node16'
  main: 'dist/index.js'
