name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  query:
    description: 'The search query for release data'
    required: true
  date:
    description: 'Set the filter for the release by date, e.g: 2023-01-01, 2023'
    required: false
  version:
    description: 'Set the filter for the release by version, e.g: 1.0'
    required: false
  limit:
    description: 'Set the limit for the number of releases to output, default: 3'
    required: false
    default: 3
outputs:
  matrix:
    description: 'The release matrix data'
  versions:
    description: 'The release versions'
  release_dates:
    description: 'The release dates'
runs:
  using: 'node16'
  main: 'dist/index.js'
