name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test-1, query=nginx
      id: test-1
      uses: ./
      with:
        query: nginx
    - name: test-2, query=nginx, limit=10
      id: test-2
      uses: ./
      with:
        query: nginx
        limit: 10
    - name: test-3, query=nginx, date=2022
      id: test-3
      uses: ./
      with:
        query: nginx
        date: 2022
    - name: test-4, query=nginx, version=1.22
      id: test-4
      uses: ./
      with:
        query: nginx
        version: 1.22
    - name: test-5, query=nginx, date=2022, version=1.22
      id: test-5
      uses: ./
      with:
        query: nginx
        date: 2022
        version: 1.22
    outputs:
      test-1: ${{ steps.test-1.outputs.matrix }}
      test-2: ${{ steps.test-2.outputs.matrix }}
      test-3: ${{ steps.test-3.outputs.matrix }}
      test-4: ${{ steps.test-4.outputs.matrix }}
      test-5: ${{ steps.test-5.outputs.matrix }}
  validate:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: test-1
      run: echo '${{ needs.test.outputs.test-1 }}'
    - name: test-2
      run: echo '${{ needs.test.outputs.test-2 }}'
    - name: test-3
      run: echo '${{ needs.test.outputs.test-3 }}'
    - name: test-4
      run: echo '${{ needs.test.outputs.test-4 }}'
    - name: test-5
      run: echo '${{ needs.test.outputs.test-5 }}'
